// Emit: TemporalTargetGraph → TypeScript code artifacts.
// Spec 33 — §19.

import { TemporalTargetError } from "./errors.js";
import type { Condition } from "@sverka/workflow";
import type { TemporalTargetGraph, TemporalWorkflow, TemporalActivity, GeneratedArtifact } from "./types.js";

/**
 * Emit a TemporalTargetGraph as TypeScript code artifacts.
 * Produces two files: <name>.workflow.ts and <name>.activities.ts.
 */
export function emitTemporal(targetGraph: TemporalTargetGraph): readonly GeneratedArtifact[] {
  try {
    const baseName = targetGraph.name;
    return [
      { path: `${baseName}.workflow.ts`, content: emitWorkflow(targetGraph) },
      { path: `${baseName}.activities.ts`, content: emitActivities(targetGraph) },
    ];
  } catch (err) {
    throw new TemporalTargetError(
      `failed to emit Temporal code: ${err instanceof Error ? err.message : String(err)}`,
      "EMIT_FAILED",
      err,
    );
  }
}

/**
 * Generate the workflow TypeScript file.
 */
function emitWorkflow(graph: TemporalTargetGraph): string {
  const lines: string[] = [
    `// Generated by Sverka — Temporal workflow target. Do not edit.`,
    `import { proxyActivities } from "@temporalio/workflow";`,
    `import type * as activities from "./${graph.name}.activities.js";`,
    ``,
    `const { runStep } = proxyActivities<typeof activities>({`,
    `  startToCloseTimeout: "5m",`,
    `  taskQueue: "${graph.taskQueue}",`,
    `});`,
    ``,
  ];

  for (const wf of graph.workflows) {
    lines.push(...emitWorkflowHandler(wf));
    lines.push("");
  }

  return lines.join("\n");
}

/**
 * Convert an entry ID to a valid TypeScript identifier.
 * Prefixes with underscore if the first character is a digit.
 */
function toIdentifier(entryId: string): string {
  const sanitized = entryId.replace(/[^a-zA-Z0-9_$]/g, "_");
  if (/^\d/.test(sanitized)) {
    return `_${sanitized}`;
  }
  return sanitized;
}

/**
 * Emit a single workflow handler.
 */
function emitWorkflowHandler(wf: TemporalWorkflow): string[] {
  const lines: string[] = [];
  const ident = toIdentifier(wf.entryId);
  const triggerComment = wf.triggerKind === "schedule" && wf.cron
    ? ` // Trigger: schedule (${wf.cron})`
    : ` // Trigger: ${wf.triggerKind}`;

  lines.push(...[
    `export const ${ident} = async (): Promise<void> => {${triggerComment}`,
    `  let _failed = false;`,
  ]);

  const activityById = new Map(wf.activities.map((a) => [a.stepId, a]));

  for (const stepId of wf.sequence) {
    const activity = activityById.get(stepId);
    if (!activity) continue;
    lines.push(...emitActivityCall(activity));
  }

  lines.push(...[
    `  if (_failed) throw new Error("workflow failed");`,
    `});`,
  ]);
  return lines;
}

/**
 * Emit a single activity call with retry, timeout, and condition.
 */
function emitActivityCall(activity: TemporalActivity): string[] {
  const lines: string[] = [];
  const guard = conditionGuard(activity.condition);

  // Surface lowering warnings (background execution, dropped non-shell ops,
  // secret references in commands) as comments in the generated workflow.
  if (activity.warnings !== undefined) {
    for (const w of activity.warnings) {
      lines.push(`  // WARNING: ${w}`);
    }
  }

  // When a step has both a timeout and a retry policy, Temporal may retry the
  // activity after the timeout fires without stopping the synchronous shell
  // process, leaving an orphaned process behind. Surface this as a comment so
  // callers know to use an AbortController in the activity to enforce
  // cancellation.
  if (activity.retry !== undefined && activity.timeoutMs !== undefined) {
    lines.push(
      `  // WARNING: this step has both a timeout and a retry policy; on timeout the synchronous shell process may be left orphaned. Use an AbortController in the activity to enforce cancellation.`,
    );
  }

  // Build activity options with retry and timeout
  const opts: string[] = [];
  if (activity.retry !== undefined) {
    opts.push(`retry: { maximumAttempts: ${activity.retry.max} }`);
  }
  if (activity.timeoutMs !== undefined) {
    opts.push(`startToCloseTimeout: "${Math.ceil(activity.timeoutMs / 1000)}s"`);
  }
  const optsStr = opts.length > 0 ? `, { ${opts.join(", ")} }` : "";

  if (guard.open) {
    lines.push(guard.open);
  }

  lines.push(`  try { await runStep("${activity.stepId}"${optsStr}); } catch { _failed = true; }`);

  if (guard.close) {
    lines.push(guard.close);
  }

  return lines;
}

/**
 * Generate condition guard lines for an activity.
 */
function conditionGuard(condition: Condition | undefined): { open: string; close: string } {
  if (condition === undefined) {
    return { open: "", close: "" };
  }

  if (condition.kind === "status") {
    switch (condition.status) {
      case "success":
        return { open: `  if (!_failed) {`, close: `  }` };
      case "failure":
        return { open: `  if (_failed) {`, close: `  }` };
      case "always":
        return { open: "", close: "" };
      case "never":
        return { open: `  if (false) { // condition: never`, close: `  }` };
    }
  }

  // Expression or Reference — cannot be evaluated at compile time
  return { open: `  // WARNING: condition kind '${condition.kind}' cannot be evaluated at compile time; step is unconditional`, close: "" };
}

/**
 * Generate the activities TypeScript file.
 * Each activity runs the actual shell commands via execFileSync — no
 * dependency on a non-existent `sverka run --step` CLI subcommand.
 *
 * Runtime env vars and workingDir are emitted into the generated activity so
 * that the produced code honors `runtime.env`, `runtime.workingDir`, and
 * `runtime.shell` instead of bypassing runtime interpolation. Secret names
 * are listed but their values are NOT embedded — they must be injected from
 * the runtime secret store at execution time.
 */
function emitActivities(graph: TemporalTargetGraph): string {
  const lines: string[] = [
    `// Generated by Sverka — Temporal activity stubs. Do not edit.`,
    `import { execFileSync } from "node:child_process";`,
    ``,
    `interface StepConfig {`,
    `  readonly commands: readonly string[];`,
    `  readonly env?: Readonly<Record<string, string>>;`,
    `  readonly cwd?: string;`,
    `  readonly shell?: string;`,
    `  readonly secrets?: readonly string[];`,
    `}`,
    ``,
    `const stepConfig: Record<string, StepConfig> = {`,
  ];

  for (const wf of graph.workflows) {
    for (const activity of wf.activities) {
      if (activity.warnings !== undefined) {
        for (const w of activity.warnings) {
          lines.push(`  // WARNING (${activity.stepId}): ${w}`);
        }
      }
      const cmds = activity.commands.map((c) => JSON.stringify(c)).join(", ");
      const fields: string[] = [`commands: [${cmds}]`];
      if (activity.env !== undefined) {
        fields.push(`env: ${JSON.stringify(activity.env)}`);
      }
      if (activity.workingDir !== undefined) {
        fields.push(`cwd: ${JSON.stringify(activity.workingDir)}`);
      }
      if (activity.shell !== undefined) {
        fields.push(`shell: ${JSON.stringify(activity.shell)}`);
      }
      if (activity.secrets !== undefined) {
        fields.push(`secrets: ${JSON.stringify(activity.secrets)}`);
      }
      lines.push(`  ${JSON.stringify(activity.stepId)}: { ${fields.join(", ")} },`);
    }
  }

  lines.push(...[
    `};`,
    ``,
    `// NOTE: stdio is set to "pipe" (not "inherit") so that secrets, PII, or`,
    `// raw responses printed by a command are not piped directly into the`,
    `// workflow log. Sanitize captured output before logging it.`,
    `export async function runStep(stepId: string): Promise<void> {`,
    `  const cfg = stepConfig[stepId];`,
    `  if (!cfg) throw new Error(\`unknown step: \${stepId}\`);`,
    `  // Secrets referenced by cfg.secrets must be injected from the runtime`,
    `  // secret store at execution time; their values are never embedded here.`,
    `  const shell = cfg.shell ?? "sh";`,
    `  for (const cmd of cfg.commands) {`,
    `    execFileSync(shell, ["-c", cmd], {`,
    `      stdio: "pipe",`,
    `      ...(cfg.cwd !== undefined ? { cwd: cfg.cwd } : {}),`,
    `      ...(cfg.env !== undefined ? { env: { ...process.env, ...cfg.env } } : {}),`,
    `    });`,
    `  }`,
    `}`,
    ``,
  ]);

  return lines.join("\n");
}
