// Emit: TemporalTargetGraph → TypeScript code artifacts.
// Spec 33 — §19.

import { TemporalTargetError } from "./errors.js";
import type { Condition } from "@sverka/workflow";
import type { TemporalTargetGraph, TemporalWorkflow, TemporalActivity, GeneratedArtifact } from "./types.js";

/**
 * Emit a TemporalTargetGraph as TypeScript code artifacts.
 * Produces two files: <name>.workflow.ts and <name>.activities.ts.
 */
export function emitTemporal(targetGraph: TemporalTargetGraph): readonly GeneratedArtifact[] {
  try {
    const baseName = targetGraph.name;
    return [
      { path: `${baseName}.workflow.ts`, content: emitWorkflow(targetGraph) },
      { path: `${baseName}.activities.ts`, content: emitActivities(targetGraph) },
    ];
  } catch (err) {
    throw new TemporalTargetError(
      `failed to emit Temporal code: ${err instanceof Error ? err.message : String(err)}`,
      "EMIT_FAILED",
      err,
    );
  }
}

/**
 * Generate the workflow TypeScript file.
 */
function emitWorkflow(graph: TemporalTargetGraph): string {
  const lines: string[] = [
    `// Generated by Sverka — Temporal workflow target. Do not edit.`,
    `import { proxyActivities } from "@temporalio/workflow";`,
    `import type * as activities from "./${graph.name}.activities.js";`,
    ``,
    `const { runStep } = proxyActivities<typeof activities>({`,
    `  startToCloseTimeout: "5m",`,
    `  taskQueue: "${graph.taskQueue}",`,
    `});`,
    ``,
  ];

  for (const wf of graph.workflows) {
    lines.push(...emitWorkflowHandler(wf));
    lines.push("");
  }

  return lines.join("\n");
}

/**
 * Convert an entry ID to a valid TypeScript identifier.
 * Prefixes with underscore if the first character is a digit.
 */
function toIdentifier(entryId: string): string {
  const sanitized = entryId.replace(/[^a-zA-Z0-9_$]/g, "_");
  if (/^\d/.test(sanitized)) {
    return `_${sanitized}`;
  }
  return sanitized;
}

/**
 * Emit a single workflow handler.
 */
function emitWorkflowHandler(wf: TemporalWorkflow): string[] {
  const lines: string[] = [];
  const ident = toIdentifier(wf.entryId);
  const triggerComment = wf.triggerKind === "schedule" && wf.cron
    ? ` // Trigger: schedule (${wf.cron})`
    : ` // Trigger: ${wf.triggerKind}`;

  lines.push(...[
    `export const ${ident} = async (): Promise<void> => {${triggerComment}`,
    `  let _failed = false;`,
  ]);

  const activityById = new Map(wf.activities.map((a) => [a.stepId, a]));

  for (const stepId of wf.sequence) {
    const activity = activityById.get(stepId);
    if (!activity) continue;
    lines.push(...emitActivityCall(activity));
  }

  lines.push(...[
    `  if (_failed) throw new Error("workflow failed");`,
    `});`,
  ]);
  return lines;
}

/**
 * Sanitize text for safe embedding in a single-line `//` comment.
 * Replaces newlines, carriage returns, Unicode line terminators (U+2028,
 * U+2029), and other control characters with spaces to prevent comment
 * termination or code injection.
 */
function sanitizeForComment(text: string): string {
  return text.replace(/[\r\n\t\u0000-\u001f\u2028\u2029]/g, " ");
}

/**
 * Emit a single activity call with retry, timeout, and condition.
 */
function emitActivityCall(activity: TemporalActivity): string[] {
  const lines: string[] = [];
  const guard = conditionGuard(activity.condition);

  // Surface lowering warnings (background execution, dropped non-shell ops,
  // secret references in commands) as comments in the generated workflow.
  // Sanitize to prevent newline injection breaking the comment.
  if (activity.warnings !== undefined) {
    for (const w of activity.warnings) {
      lines.push(`  // WARNING: ${sanitizeForComment(w)}`);
    }
  }

  // When a step has both a timeout and a retry policy, Temporal may retry the
  // activity after the timeout fires without stopping the synchronous shell
  // process, leaving an orphaned process behind. The generated activity uses
  // execFileSync which cannot be cancelled mid-execution; callers must wrap
  // long-running commands in their own timeout logic if cancellation is required.
  if (activity.retry !== undefined && activity.timeoutMs !== undefined) {
    lines.push(
      `  // WARNING: this step has both a timeout and a retry policy; on timeout the synchronous shell process cannot be cancelled by execFileSync. Wrap long-running commands in their own timeout logic if cancellation is required.`,
    );
  }

  // Build activity options with retry and timeout
  const opts: string[] = [];
  if (activity.retry !== undefined) {
    opts.push(`retry: { maximumAttempts: ${activity.retry.max} }`);
  }
  if (activity.timeoutMs !== undefined) {
    opts.push(`startToCloseTimeout: "${Math.ceil(activity.timeoutMs / 1000)}s"`);
  }
  const optsStr = opts.length > 0 ? `, { ${opts.join(", ")} }` : "";

  if (guard.open) {
    lines.push(guard.open);
  }

  lines.push(`  try { await runStep(${JSON.stringify(activity.stepId)}${optsStr}); } catch { _failed = true; }`);

  if (guard.close) {
    lines.push(guard.close);
  }

  return lines;
}

/**
 * Generate condition guard lines for an activity.
 */
function conditionGuard(condition: Condition | undefined): { open: string; close: string } {
  if (condition === undefined) {
    return { open: "", close: "" };
  }

  if (condition.kind === "status") {
    switch (condition.status) {
      case "success":
        return { open: `  if (!_failed) {`, close: `  }` };
      case "failure":
        return { open: `  if (_failed) {`, close: `  }` };
      case "always":
        return { open: "", close: "" };
      case "never":
        return { open: `  if (false) { // condition: never`, close: `  }` };
    }
  }

  // Expression or Reference — cannot be evaluated at compile time
  return { open: `  // WARNING: condition kind '${condition.kind}' cannot be evaluated at compile time; step is unconditional`, close: "" };
}

/**
 * Generate the activities TypeScript file.
 * Each activity runs the actual shell commands via execFileSync — no
 * dependency on a non-existent `sverka run --step` CLI subcommand.
 *
 * Runtime env vars and workingDir are emitted into the generated activity so
 * that the produced code honors `runtime.env`, `runtime.workingDir`, and
 * `runtime.shell` instead of bypassing runtime interpolation. Secret names
 * are listed in the config and their values are injected from `process.env`
 * at execution time — values are never embedded in generated code.
 *
 * Background commands are emitted as detached spawns (not awaited) to
 * emulate fire-and-forget execution without silently dropping the command.
 */
function emitActivities(graph: TemporalTargetGraph): string {
  const lines: string[] = [...emitActivityHeader()];
  for (const wf of graph.workflows) {
    for (const activity of wf.activities) {
      lines.push(...emitStepConfigEntry(activity));
    }
  }
  lines.push(...emitRunStepFunction());
  return lines.join("\n");
}

/**
 * Emit the file header, interface, and stepConfig opening.
 */
function emitActivityHeader(): string[] {
  return [
    `// Generated by Sverka — Temporal activity stubs. Do not edit.`,
    `import { execFileSync, spawn } from "node:child_process";`,
    ``,
    `interface StepConfig {`,
    `  readonly commands: readonly string[];`,
    `  readonly backgroundCommands?: readonly string[];`,
    `  readonly env?: Readonly<Record<string, string>>;`,
    `  readonly cwd?: string;`,
    `  readonly shell?: string;`,
    `  readonly secrets?: readonly string[];`,
    `}`,
    ``,
    `const stepConfig: Record<string, StepConfig> = {`,
  ];
}

/**
 * Emit a single stepConfig entry for an activity.
 */
function emitStepConfigEntry(activity: TemporalActivity): string[] {
  const lines: string[] = [];
  if (activity.warnings !== undefined) {
    for (const w of activity.warnings) {
      lines.push(`  // WARNING (${activity.stepId}): ${sanitizeForComment(w)}`);
    }
  }
  const cmds = activity.commands.map((c) => JSON.stringify(c)).join(", ");
  const fields: string[] = [`commands: [${cmds}]`];
  if (activity.backgroundCommands !== undefined && activity.backgroundCommands.length > 0) {
    const bgCmds = activity.backgroundCommands.map((c) => JSON.stringify(c)).join(", ");
    fields.push(`backgroundCommands: [${bgCmds}]`);
  }
  if (activity.env !== undefined) {
    fields.push(`env: ${JSON.stringify(activity.env)}`);
  }
  if (activity.workingDir !== undefined) {
    fields.push(`cwd: ${JSON.stringify(activity.workingDir)}`);
  }
  if (activity.shell !== undefined) {
    fields.push(`shell: ${JSON.stringify(activity.shell)}`);
  }
  if (activity.secrets !== undefined) {
    fields.push(`secrets: ${JSON.stringify(activity.secrets)}`);
  }
  lines.push(`  ${JSON.stringify(activity.stepId)}: { ${fields.join(", ") } },`);
  return lines;
}

/**
 * Emit the secret interpolation and shell-flag helper functions.
 */
function emitHelpers(): string[] {
  return [
    `};`,
    ``,
    `// NOTE: stdio is set to "pipe" (not "inherit") so that secrets, PII, or`,
    `// raw responses printed by a command are not piped directly into the`,
    `// workflow log. maxBuffer is set to 10 MiB to avoid ENOBUFS on commands`,
    `// that produce large output. Sanitize captured output before logging it.`,
    `const SECRET_REF = /secrets\\.([A-Za-z_][A-Za-z0-9_]*)/g;`,
    ``,
    `// Replace \`secrets.NAME\` references in a command with \`\${NAME}\` so the`,
    `// shell resolves them from the environment. Secret values are injected into`,
    `// childEnv from process.env — they are never embedded in generated code.`,
    `function interpolateSecrets(cmd: string): string {`,
    `  return cmd.replace(SECRET_REF, (_m, name: string) => \`\${\${name}}\`);`,
    `}`,
    ``,
    `// Select the command flag for the shell: -c for sh/bash/zsh, /c for cmd,`,
    `// -Command for PowerShell. Defaults to -c for unknown shells.`,
    `function shellFlag(shell: string): string {`,
    `  if (shell === "cmd" || shell === "cmd.exe") return "/c";`,
    `  if (shell === "powershell" || shell === "pwsh") return "-Command";`,
    `  return "-c";`,
    `}`,
    ``,
  ];
}

/**
 * Emit the RunStepOptions interface and runStep function signature.
 */
function emitRunStepSignature(): string[] {
  return [
    `interface RunStepOptions {`,
    `  retry?: { maximumAttempts: number };`,
    `  startToCloseTimeout?: string;`,
    `}`,
    ``,
    `export async function runStep(stepId: string, opts?: RunStepOptions): Promise<void> {`,
    `  const cfg = stepConfig[stepId];`,
    `  if (!cfg) throw new Error(\`unknown step: \${stepId}\`);`,
    `  const shell = cfg.shell ?? "sh";`,
    `  const flag = shellFlag(shell);`,
    `  // Build the child process environment: start with process.env, overlay`,
    `  // step-level env, then inject secret values from process.env for each`,
    `  // name in cfg.secrets. Secret values are never embedded in generated code.`,
    `  const childEnv: Record<string, string | undefined> = { ...process.env, ...(cfg.env ?? {}) };`,
    `  if (cfg.secrets !== undefined) {`,
    `    for (const name of cfg.secrets) {`,
    `      if (process.env[name] !== undefined) {`,
    `        childEnv[name] = process.env[name];`,
    `      }`,
    `    }`,
    `  }`,
  ];
}

/**
 * Emit the background and foreground command execution body of runStep.
 */
function emitRunStepExecution(): string[] {
  return [
    `  // Background commands are spawned detached (fire-and-forget) and not awaited.`,
    `  if (cfg.backgroundCommands !== undefined) {`,
    `    for (const cmd of cfg.backgroundCommands) {`,
    `      spawn(shell, [flag, interpolateSecrets(cmd)], {`,
    `        stdio: "ignore",`,
    `        detached: true,`,
    `        ...(cfg.cwd !== undefined ? { cwd: cfg.cwd } : {}),`,
    `        env: childEnv,`,
    `      }).unref();`,
    `    }`,
    `  }`,
    `  // Foreground commands are awaited synchronously with retry support.`,
    `  const maxAttempts = opts?.retry?.maximumAttempts ?? 1;`,
    `  for (let attempt = 0; attempt < maxAttempts; attempt++) {`,
    `    try {`,
    `      for (const cmd of cfg.commands) {`,
    `        execFileSync(shell, [flag, interpolateSecrets(cmd)], {`,
    `          stdio: "pipe",`,
    `          maxBuffer: 10 * 1024 * 1024,`,
    `          ...(cfg.cwd !== undefined ? { cwd: cfg.cwd } : {}),`,
    `          env: childEnv,`,
    `        });`,
    `      }`,
    `      return;`,
    `    } catch (e) {`,
    `      if (attempt < maxAttempts - 1) continue;`,
    `      throw e;`,
    `    }`,
    `  }`,
    `}`,
    ``,
  ];
}

/**
 * Emit the runStep function that executes foreground and background commands.
 */
function emitRunStepBody(): string[] {
  return [...emitRunStepSignature(), ...emitRunStepExecution()];
}

/**
 * Emit the closing brace, runStep function, and secret interpolation helper.
 */
function emitRunStepFunction(): string[] {
  return [...emitHelpers(), ...emitRunStepBody()];
}
