// Emit: TemporalTargetGraph → TypeScript code artifacts.
// Spec 33 — §19.

import { TemporalTargetError } from "./errors.js";
import type { Condition } from "@sverka/workflow";
import type { TemporalTargetGraph, TemporalWorkflow, TemporalActivity, GeneratedArtifact } from "./types.js";

/**
 * Emit a TemporalTargetGraph as TypeScript code artifacts.
 * Produces two files: <name>.workflow.ts and <name>.activities.ts.
 */
export function emitTemporal(targetGraph: TemporalTargetGraph): readonly GeneratedArtifact[] {
  try {
    const baseName = targetGraph.name;
    return [
      { path: `${baseName}.workflow.ts`, content: emitWorkflow(targetGraph) },
      { path: `${baseName}.activities.ts`, content: emitActivities(targetGraph) },
    ];
  } catch (err) {
    throw new TemporalTargetError(
      `failed to emit Temporal code: ${err instanceof Error ? err.message : String(err)}`,
      "EMIT_FAILED",
      err,
    );
  }
}

/**
 * Generate the workflow TypeScript file.
 */
function emitWorkflow(graph: TemporalTargetGraph): string {
  const lines: string[] = [
    `// Generated by Sverka — Temporal workflow target. Do not edit.`,
    `import { proxyActivities } from "@temporalio/workflow";`,
    `import type * as activities from "./${graph.name}.activities.js";`,
    ``,
    `const { runStep } = proxyActivities<typeof activities>({`,
    `  startToCloseTimeout: "5m",`,
    `  taskQueue: "${graph.taskQueue}",`,
    `});`,
    ``,
  ];

  for (const wf of graph.workflows) {
    lines.push(...emitWorkflowHandler(wf));
    lines.push("");
  }

  return lines.join("\n");
}

/**
 * Convert an entry ID to a valid TypeScript identifier.
 * Prefixes with underscore if the first character is a digit.
 */
function toIdentifier(entryId: string): string {
  const sanitized = entryId.replace(/[^a-zA-Z0-9_$]/g, "_");
  if (/^\d/.test(sanitized)) {
    return `_${sanitized}`;
  }
  return sanitized;
}

/**
 * Emit a single workflow handler.
 */
function emitWorkflowHandler(wf: TemporalWorkflow): string[] {
  const lines: string[] = [];
  const ident = toIdentifier(wf.entryId);
  const triggerComment = wf.triggerKind === "schedule" && wf.cron
    ? ` // Trigger: schedule (${wf.cron})`
    : ` // Trigger: ${wf.triggerKind}`;

  lines.push(...[
    `export const ${ident} = async (): Promise<void> => {${triggerComment}`,
    `  let _failed = false;`,
  ]);

  const activityById = new Map(wf.activities.map((a) => [a.stepId, a]));

  for (const stepId of wf.sequence) {
    const activity = activityById.get(stepId);
    if (!activity) continue;
    lines.push(...emitActivityCall(activity));
  }

  lines.push(...[
    `  if (_failed) throw new Error("workflow failed");`,
    `});`,
  ]);
  return lines;
}

/**
 * Emit a single activity call with retry, timeout, and condition.
 */
function emitActivityCall(activity: TemporalActivity): string[] {
  const lines: string[] = [];
  const guard = conditionGuard(activity.condition);

  // Build activity options with retry and timeout
  const opts: string[] = [];
  if (activity.retry !== undefined) {
    opts.push(`retry: { maximumAttempts: ${activity.retry.max} }`);
  }
  if (activity.timeoutMs !== undefined) {
    opts.push(`startToCloseTimeout: "${Math.ceil(activity.timeoutMs / 1000)}s"`);
  }
  const optsStr = opts.length > 0 ? `, { ${opts.join(", ")} }` : "";

  if (guard.open) {
    lines.push(guard.open);
  }

  lines.push(`  try { await runStep("${activity.stepId}"${optsStr}); } catch { _failed = true; }`);

  if (guard.close) {
    lines.push(guard.close);
  }

  return lines;
}

/**
 * Generate condition guard lines for an activity.
 */
function conditionGuard(condition: Condition | undefined): { open: string; close: string } {
  if (condition === undefined) {
    return { open: "", close: "" };
  }

  if (condition.kind === "status") {
    switch (condition.status) {
      case "success":
        return { open: `  if (!_failed) {`, close: `  }` };
      case "failure":
        return { open: `  if (_failed) {`, close: `  }` };
      case "always":
        return { open: "", close: "" };
      case "never":
        return { open: `  if (false) { // condition: never`, close: `  }` };
    }
  }

  // Expression or Reference — cannot be evaluated at compile time
  return { open: `  // WARNING: condition kind '${condition.kind}' cannot be evaluated at compile time; step is unconditional`, close: "" };
}

/**
 * Generate the activities TypeScript file.
 * Each activity runs the actual shell commands via execFileSync — no
 * dependency on a non-existent `sverka run --step` CLI subcommand.
 */
function emitActivities(graph: TemporalTargetGraph): string {
  const lines: string[] = [
    `// Generated by Sverka — Temporal activity stubs. Do not edit.`,
    `import { execFileSync } from "node:child_process";`,
    ``,
    `const stepCommands: Record<string, readonly string[]> = {`,
  ];

  for (const wf of graph.workflows) {
    for (const activity of wf.activities) {
      const cmds = activity.commands.map((c) => JSON.stringify(c)).join(", ");
      lines.push(`  ${JSON.stringify(activity.stepId)}: [${cmds}],`);
    }
  }

  lines.push(...[
    `};`,
    ``,
    `export async function runStep(stepId: string): Promise<void> {`,
    `  const commands = stepCommands[stepId];`,
    `  if (!commands) throw new Error(\`unknown step: \${stepId}\`);`,
    `  for (const cmd of commands) {`,
    `    execFileSync("sh", ["-c", cmd], { stdio: "inherit" });`,
    `  }`,
    `}`,
    ``,
  ]);

  return lines.join("\n");
}
