// Emit: InngestTargetGraph → TypeScript Inngest function artifact.
// Spec 35 — §19.

import { InngestTargetError } from "./errors.js";
import { sanitizeForComment, conditionGuard } from "../internal/sanitize.js";
import type { InngestTargetGraph, InngestFunction, InngestStep, GeneratedArtifact } from "./types.js";

/**
 * Emit an InngestTargetGraph as a TypeScript Inngest function artifact.
 * Produces one <appId>.ts file.
 */
export function emitInngest(targetGraph: InngestTargetGraph): readonly GeneratedArtifact[] {
  try {
    const fileName = `${targetGraph.appId}.ts`;
    return [{ path: fileName, content: emitFunctions(targetGraph) }];
  } catch (err) {
    throw new InngestTargetError(
      `failed to emit Inngest code: ${err instanceof Error ? err.message : String(err)}`,
      "EMIT_FAILED",
      err,
    );
  }
}

/**
 * Generate the Inngest functions TypeScript file.
 */
function emitFunctions(graph: InngestTargetGraph): string {
  const lines: string[] = [
    `// Generated by Sverka — Inngest function target. Do not edit.`,
    `import { Inngest } from "inngest";`, // nosemgrep: missing-template-string-indicator
    `import { execSync } from "node:child_process";`, // nosemgrep: missing-template-string-indicator
    ``,
    `const inngest = new Inngest({ id: ${JSON.stringify(graph.appId)} });`,
    ``,
  ];

  for (const fn of graph.functions) {
    lines.push(...emitFunction(fn, graph.appId));
    lines.push("");
  }

  return lines.join("\n");
}

/**
 * Emit a single Inngest function.
 */
function emitFunction(fn: InngestFunction, appId: string): string[] {
  const lines: string[] = [];
  const ident = toIdentifier(fn.entryId);
  const retries = fn.steps.some((s) => s.retry !== undefined)
    ? fn.steps.find((s) => s.retry !== undefined)?.retry?.max ?? 3
    : 3;

  const trigger = fn.triggerKind === "schedule" && fn.cron
    ? `{ cron: ${JSON.stringify(fn.cron)} }`
    : `{ event: ${JSON.stringify("sverka/" + fn.entryId)} }`;

  lines.push(...[
    `export const ${ident} = inngest.createFunction(`,
    `  { id: ${JSON.stringify(fn.entryId)}, name: ${JSON.stringify(appId)}, retries: ${retries} },`,
    `  ${trigger},`,
    `  async ({ step }) => {`, // nosemgrep: missing-template-string-indicator
    `    let _failed = false;`,
  ]);

  const stepById = new Map(fn.steps.map((s) => [s.stepId, s]));

  for (const stepId of fn.sequence) {
    const step = stepById.get(stepId);
    if (!step) continue;
    lines.push(...emitStepRun(step));
  }

  lines.push(...[
    `    if (_failed) throw new Error("function failed");`,
    `    return { status: "complete" };`, // nosemgrep: missing-template-string-indicator
    `  },`,
    `);`,
  ]);
  return lines;
}

/**
 * Emit a single step.run call.
 */
function emitStepRun(step: InngestStep): string[] {
  const lines: string[] = [];
  const shortName = step.stepId.includes("/") ? step.stepId.split("/").pop()! : step.stepId;

  const guard = conditionGuard(step.condition, "    ");

  if (guard.open) {
    lines.push(guard.open);
  }

  // Skip downstream steps after a failure (fail-fast) — throw to ensure
  // the function reports failure rather than returning success.
  // But allow `failure` and `always` condition steps to run so cleanup
  // and notification steps can still execute.
  const isFailureOrAlways = step.condition?.kind === "status" &&
    (step.condition.status === "failure" || step.condition.status === "always");
  if (!isFailureOrAlways) {
    lines.push(`    if (_failed) throw new Error("function failed");`);
  }

  if (step.matrix !== undefined) {
    lines.push(...emitMatrixStep(step, shortName));
  } else {
    lines.push(...emitSimpleStep(step, shortName));
  }

  if (guard.close) {
    lines.push(guard.close);
  }

  return lines;
}

/**
 * Emit a matrix-iterated step.run call via Promise.all.
 */
function emitMatrixStep(step: InngestStep, shortName: string): string[] {
  const lines: string[] = [`    // Matrix: emulated via Promise.all`];
  const matrixKeys = Object.keys(step.matrix!.dimensions);
  if (matrixKeys.length === 0) return lines;
  const key = matrixKeys[0]!;
  const values = step.matrix!.dimensions[key] ?? [];
  const serializedValues = values.map((v) => JSON.stringify(String(v))).join(", ");
  lines.push(...[
    `    await Promise.all([${serializedValues}].map(async () => {`,
    `      try {`,
    `        await step.run(${JSON.stringify(shortName)}, async () => {`,
    `          // sverka run --step ${sanitizeForComment(step.stepId)}`,
  ]);
  for (const cmd of step.commands) {
    lines.push(`          execSync(${JSON.stringify(cmd)}, { stdio: "inherit" });`); // nosemgrep: missing-template-string-indicator
  }
  lines.push(...[
    `        });`,
    `      } catch { _failed = true; }`, // nosemgrep: missing-template-string-indicator
    `    }));`,
  ]);
  return lines;
}

/**
 * Emit a simple (non-matrix) step.run call.
 */
function emitSimpleStep(step: InngestStep, shortName: string): string[] {
  const lines: string[] = [];
  if (step.timeout !== undefined) {
    lines.push(`    // timeout: ${Math.ceil(step.timeout / 1000)}s (Inngest step.run has no per-step timeout; use function-level timeouts.finish)`);
  }
  lines.push(...[
    `    try {`,
    `      await step.run(${JSON.stringify(shortName)}, async () => {`,
    `        // sverka run --step ${sanitizeForComment(step.stepId)}`,
  ]);
  for (const cmd of step.commands) {
    lines.push(`        execSync(${JSON.stringify(cmd)}, { stdio: "inherit" });`); // nosemgrep: missing-template-string-indicator
  }
  lines.push(...[
    `      });`,
    `    } catch { _failed = true; }`, // nosemgrep: missing-template-string-indicator
  ]);
  return lines;
}



/**
 * Convert an entry ID to a valid TypeScript identifier.
 * Prefixes with underscore if the first character is a digit.
 * Prefixes with underscore if the result is a reserved word.
 */
const RESERVED_WORDS = new Set([
  "break", "case", "catch", "class", "const", "continue", "debugger", "default",
  "delete", "do", "else", "enum", "export", "extends", "false", "finally", "for",
  "function", "if", "import", "in", "instanceof", "new", "null", "return", "super",
  "switch", "this", "throw", "true", "try", "typeof", "var", "void", "while", "with",
  "as", "async", "await", "yield", "let", "static", "implements", "interface", "package",
  "private", "protected", "public", "type", "from", "of", "get", "set",
]);

function toIdentifier(entryId: string): string {
  const sanitized = entryId.replace(/[^a-zA-Z0-9_$]/g, "_");
  const base = /^\d/.test(sanitized) ? `_${sanitized}` : sanitized;
  return RESERVED_WORDS.has(base) ? `_${base}` : base;
}
