// Emit: InngestTargetGraph → TypeScript Inngest function artifact.
// Spec 35 — §19.

import { InngestTargetError } from "./errors.js";
import type { InngestTargetGraph, InngestFunction, InngestStep, GeneratedArtifact } from "./types.js";

/**
 * Emit an InngestTargetGraph as a TypeScript Inngest function artifact.
 * Produces one <appId>.ts file.
 */
export function emitInngest(targetGraph: InngestTargetGraph): readonly GeneratedArtifact[] {
  try {
    const fileName = `${targetGraph.appId}.ts`;
    return [{ path: fileName, content: emitFunctions(targetGraph) }];
  } catch (err) {
    throw new InngestTargetError(
      `failed to emit Inngest code: ${err instanceof Error ? err.message : String(err)}`,
      "EMIT_FAILED",
      err,
    );
  }
}

/**
 * Generate the Inngest functions TypeScript file.
 */
function emitFunctions(graph: InngestTargetGraph): string {
  const lines: string[] = [
    `// Generated by Sverka — Inngest function target. Do not edit.`,
    `import { createFunction } from "@inngest/agent-kit";`,
    `import { execSync } from "node:child_process";`,
    ``,
  ];

  for (const fn of graph.functions) {
    lines.push(...emitFunction(fn, graph.appId));
    lines.push("");
  }

  return lines.join("\n");
}

/**
 * Emit a single Inngest function.
 */
function emitFunction(fn: InngestFunction, appId: string): string[] {
  const lines: string[] = [];
  const ident = toIdentifier(fn.entryId);
  const retries = fn.steps.some((s) => s.retry !== undefined)
    ? fn.steps.find((s) => s.retry !== undefined)?.retry?.max ?? 3
    : 3;

  const trigger = fn.triggerKind === "schedule" && fn.cron
    ? `{ cron: "${fn.cron}" }`
    : `{ event: "sverka/${fn.entryId}" }`;

  lines.push(`export const ${ident} = createFunction(`);
  lines.push(`  { id: "${fn.entryId}", name: "${appId}", retries: ${retries} },`);
  lines.push(`  ${trigger},`);
  lines.push(`  async ({ step }) => {`);

  const stepById = new Map(fn.steps.map((s) => [s.stepId, s]));

  for (const stepId of fn.sequence) {
    const step = stepById.get(stepId);
    if (!step) continue;
    lines.push(...emitStepRun(step));
  }

  lines.push(`    return { status: "complete" };`);
  lines.push(`  },`);
  lines.push(`);`);
  return lines;
}

/**
 * Emit a single step.run call.
 */
function emitStepRun(step: InngestStep): string[] {
  const lines: string[] = [];
  const shortName = step.stepId.includes("/") ? step.stepId.split("/").pop()! : step.stepId;

  if (step.condition !== undefined) {
    lines.push(`    if (true) {`);
  }

  if (step.matrix !== undefined) {
    lines.push(`    // Matrix: emulated via Promise.all`);
    const matrixKeys = Object.keys(step.matrix.dimensions);
    if (matrixKeys.length > 0) {
      const key = matrixKeys[0]!;
      const values = step.matrix.dimensions[key] ?? [];
      lines.push(`    await Promise.all([${values.map((v) => `"${v}"`).join(", ")}].map(async (${key}) => {`);
      lines.push(`      await step.run("${shortName}", async () => {`);
      lines.push(`        // sverka run --step ${step.stepId}`);
      for (const cmd of step.commands) {
        lines.push(`        execSync(${JSON.stringify(cmd)}, { stdio: "inherit" });`);
      }
      lines.push(`      });`);
      lines.push(`    }));`);
    }
  } else {
    const timeoutOpt = step.timeout !== undefined ? `, { timeout: ${Math.ceil(step.timeout / 1000)} }` : "";
    lines.push(`    await step.run("${shortName}", async () => {`);
    lines.push(`      // sverka run --step ${step.stepId}`);
    for (const cmd of step.commands) {
      lines.push(`      execSync(${JSON.stringify(cmd)}, { stdio: "inherit" });`);
    }
    lines.push(`    }${timeoutOpt});`);
  }

  if (step.condition !== undefined) {
    lines.push(`    }`);
  }

  return lines;
}

/**
 * Convert an entry ID to a valid TypeScript identifier.
 */
function toIdentifier(entryId: string): string {
  return entryId.replace(/[^a-zA-Z0-9_$]/g, "_");
}
