// Emit: InngestTargetGraph → TypeScript Inngest function artifact.
// Spec 35 — §19.

import { InngestTargetError } from "./errors.js";
import type { Condition } from "@sverka/workflow";
import type { InngestTargetGraph, InngestFunction, InngestStep, GeneratedArtifact } from "./types.js";

/**
 * Emit an InngestTargetGraph as a TypeScript Inngest function artifact.
 * Produces one <appId>.ts file.
 */
export function emitInngest(targetGraph: InngestTargetGraph): readonly GeneratedArtifact[] {
  try {
    const fileName = `${targetGraph.appId}.ts`;
    return [{ path: fileName, content: emitFunctions(targetGraph) }];
  } catch (err) {
    throw new InngestTargetError(
      `failed to emit Inngest code: ${err instanceof Error ? err.message : String(err)}`,
      "EMIT_FAILED",
      err,
    );
  }
}

/**
 * Generate the Inngest functions TypeScript file.
 */
function emitFunctions(graph: InngestTargetGraph): string {
  const lines: string[] = [
    `// Generated by Sverka — Inngest function target. Do not edit.`,
    `import { Inngest } from "inngest";`,
    `import { execSync } from "node:child_process";`,
    ``,
    `const inngest = new Inngest({ id: "${graph.appId}" });`,
    ``,
  ];

  for (const fn of graph.functions) {
    lines.push(...emitFunction(fn, graph.appId));
    lines.push("");
  }

  return lines.join("\n");
}

/**
 * Emit a single Inngest function.
 */
function emitFunction(fn: InngestFunction, appId: string): string[] {
  const lines: string[] = [];
  const ident = toIdentifier(fn.entryId);
  const retries = fn.steps.some((s) => s.retry !== undefined)
    ? fn.steps.find((s) => s.retry !== undefined)?.retry?.max ?? 3
    : 3;

  const trigger = fn.triggerKind === "schedule" && fn.cron
    ? `{ cron: "${fn.cron}" }`
    : `{ event: "sverka/${fn.entryId}" }`;

  lines.push(...[
    `export const ${ident} = inngest.createFunction(`,
    `  { id: "${fn.entryId}", name: "${appId}", retries: ${retries} },`,
    `  ${trigger},`,
    `  async ({ step }) => {`,
    `    let _failed = false;`,
  ]);

  const stepById = new Map(fn.steps.map((s) => [s.stepId, s]));

  for (const stepId of fn.sequence) {
    const step = stepById.get(stepId);
    if (!step) continue;
    lines.push(...emitStepRun(step));
  }

  lines.push(...[
    `    if (_failed) throw new Error("function failed");`,
    `    return { status: "complete" };`,
    `  },`,
    `);`,
  ]);
  return lines;
}

/**
 * Emit a single step.run call.
 */
function emitStepRun(step: InngestStep): string[] {
  const lines: string[] = [];
  const shortName = step.stepId.includes("/") ? step.stepId.split("/").pop()! : step.stepId;

  const guard = conditionGuard(step.condition);

  if (guard.open) {
    lines.push(guard.open);
  }

  if (step.matrix !== undefined) {
    lines.push(...emitMatrixStep(step, shortName));
  } else {
    lines.push(...emitSimpleStep(step, shortName));
  }

  if (guard.close) {
    lines.push(guard.close);
  }

  return lines;
}

/**
 * Emit a matrix-iterated step.run call via Promise.all.
 */
function emitMatrixStep(step: InngestStep, shortName: string): string[] {
  const lines: string[] = [`    // Matrix: emulated via Promise.all`];
  const matrixKeys = Object.keys(step.matrix!.dimensions);
  if (matrixKeys.length === 0) return lines;
  const key = matrixKeys[0]!;
  const values = step.matrix!.dimensions[key] ?? [];
  const serializedValues = values.map((v) => JSON.stringify(String(v))).join(", ");
  lines.push(...[
    `    await Promise.all([${serializedValues}].map(async (${key}) => {`,
    `      try {`,
    `        await step.run("${shortName}", async () => {`,
    `          // sverka run --step ${step.stepId}`,
  ]);
  for (const cmd of step.commands) {
    lines.push(`          execSync(${JSON.stringify(cmd)}, { stdio: "inherit" });`);
  }
  lines.push(...[
    `        });`,
    `      } catch { _failed = true; }`,
    `    }));`,
  ]);
  return lines;
}

/**
 * Emit a simple (non-matrix) step.run call.
 */
function emitSimpleStep(step: InngestStep, shortName: string): string[] {
  const lines: string[] = [];
  if (step.timeout !== undefined) {
    lines.push(`    // timeout: ${Math.ceil(step.timeout / 1000)}s (Inngest step.run has no per-step timeout; use function-level timeouts.finish)`);
  }
  lines.push(...[
    `    try {`,
    `      await step.run("${shortName}", async () => {`,
    `        // sverka run --step ${step.stepId}`,
  ]);
  for (const cmd of step.commands) {
    lines.push(`        execSync(${JSON.stringify(cmd)}, { stdio: "inherit" });`);
  }
  lines.push(...[
    `      });`,
    `    } catch { _failed = true; }`,
  ]);
  return lines;
}

/**
 * Generate condition guard lines for a step.
 */
function conditionGuard(condition: Condition | undefined): { open: string; close: string } {
  if (condition === undefined) {
    return { open: "", close: "" };
  }

  if (condition.kind === "status") {
    switch (condition.status) {
      case "success":
        return { open: `    if (!_failed) {`, close: `    }` };
      case "failure":
        return { open: `    if (_failed) {`, close: `    }` };
      case "always":
        return { open: "", close: "" };
      case "never":
        return { open: `    if (false) { // condition: never`, close: `    }` };
    }
  }

  // Expression or Reference — cannot be evaluated at compile time
  return { open: `    // WARNING: condition kind '${condition.kind}' cannot be evaluated at compile time; step is unconditional`, close: "" };
}

/**
 * Convert an entry ID to a valid TypeScript identifier.
 * Prefixes with underscore if the first character is a digit.
 */
function toIdentifier(entryId: string): string {
  const sanitized = entryId.replace(/[^a-zA-Z0-9_$]/g, "_");
  if (/^\d/.test(sanitized)) {
    return `_${sanitized}`;
  }
  return sanitized;
}
