// Emit: DaggerTargetGraph → TypeScript Dagger Module artifact.
// Spec 34 — §19.

import { DaggerTargetError } from "./errors.js";
import type { Condition } from "@sverka/workflow";
import type { DaggerTargetGraph, DaggerStep, GeneratedArtifact } from "./types.js";

/**
 * Emit a DaggerTargetGraph as a TypeScript Dagger Module artifact.
 * Produces one <moduleName>.ts file.
 */
export function emitDagger(targetGraph: DaggerTargetGraph): readonly GeneratedArtifact[] {
  try {
    const fileName = `${targetGraph.moduleName}.ts`;
    return [{ path: fileName, content: emitModule(targetGraph) }];
  } catch (err) {
    throw new DaggerTargetError(
      `failed to emit Dagger module: ${err instanceof Error ? err.message : String(err)}`,
      "EMIT_FAILED",
      err,
    );
  }
}

/**
 * Generate the Dagger Module TypeScript file.
 */
function emitModule(graph: DaggerTargetGraph): string {
  const defaultImage = graph.steps.find((s) => s.runtime.mode === "container" && s.runtime.image)?.runtime.image ?? "node:24";
  const lines: string[] = [
    `// Generated by Sverka — Dagger Module target. Do not edit.`,
    `import { dag, object, func } from "@dagger.io/dagger";`,
    ``,
    `@object()`,
    `export class SverkaPipeline {`,
    `  @func()`,
    `  async ${toIdentifier(graph.entryId)}(): Promise<string> {`,
    `    let ctx = dag.container().from("${defaultImage}").withMountedDirectory("/src", dag.git(".").tree()).withWorkdir("/src");`,
    `    let _failed = false;`,
  ];

  const stepById = new Map(graph.steps.map((s) => [s.stepId, s]));

  for (const stepId of graph.sequence) {
    const step = stepById.get(stepId);
    if (!step) continue;
    lines.push(...emitStep(step));
  }

  lines.push(`    if (_failed) throw new Error("pipeline failed");`);
  lines.push(`    return ctx.stdout();`);
  lines.push(`  }`);
  lines.push(`}`);
  lines.push("");

  return lines.join("\n");
}

/**
 * Emit a single step as Dagger withExec chain calls.
 */
function emitStep(step: DaggerStep): string[] {
  const lines: string[] = [];

  if (step.runtime.mode === "host") {
    lines.push(`    // Host runtime is unsupported by Dagger; using container context.`);
  }

  const guard = conditionGuard(step.condition);

  if (guard.open) {
    lines.push(guard.open);
  }

  if (step.retry !== undefined) {
    lines.push(`    // Retry wrapper (max ${step.retry.max} attempts)`);
    lines.push(`    for (let attempt = 0; attempt < ${step.retry.max}; attempt++) {`);
    lines.push(`      try {`);
    lines.push(`        let retryCtx = ctx;`);
  }

  for (const command of step.commands) {
    const cmdStr = JSON.stringify(command);
    if (step.timeout !== undefined) {
      lines.push(`    // timeout: ${Math.ceil(step.timeout / 1000)}s (Dagger has no withTimeout; enforced by runner)`);
    }
    if (step.retry !== undefined) {
      lines.push(`        retryCtx = retryCtx.withExec(["sh", "-c", ${cmdStr}]);`);
    } else {
      lines.push(`    ctx = ctx.withExec(["sh", "-c", ${cmdStr}]);`);
    }
  }

  if (step.retry !== undefined) {
    lines.push(`        retryCtx.stdout(); // execute graph to surface errors`);
    lines.push(`        ctx = retryCtx;`);
  }

  if (step.matrix !== undefined) {
    lines.push(`    // Matrix: emulated via loop`);
    for (const [key, values] of Object.entries(step.matrix.dimensions)) {
      lines.push(`    for (const ${key} of [${values.map((v) => `"${v}"`).join(", ")}]) {`);
      lines.push(`      // matrix iteration: ${key}`);
      lines.push(`    }`);
    }
  }

  if (step.retry !== undefined) {
    lines.push(`        break;`);
    lines.push(`      } catch (err) {`);
    lines.push(`        if (attempt === ${step.retry.max - 1}) throw err;`);
    lines.push(`      }`);
    lines.push(`    }`);
  }

  // Track failure for condition guards
  const hasCatch = step.condition !== undefined || guard.alwaysWrap;
  if (hasCatch && step.condition?.kind === "status" && step.condition.status === "always") {
    lines.push(`    try { /* always: swallow errors */ } catch { /* no-op */ }`);
  }

  if (guard.close) {
    lines.push(guard.close);
  }

  return lines;
}

/**
 * Generate condition guard lines for a step.
 */
function conditionGuard(condition: Condition | undefined): { open: string; close: string; alwaysWrap: boolean } {
  if (condition === undefined) {
    return { open: "", close: "", alwaysWrap: false };
  }

  if (condition.kind === "status") {
    switch (condition.status) {
      case "success":
        return { open: `    if (!_failed) {`, close: `    }`, alwaysWrap: false };
      case "failure":
        return { open: `    if (_failed) {`, close: `    }`, alwaysWrap: false };
      case "always":
        return { open: "", close: "", alwaysWrap: true };
      case "never":
        return { open: `    if (false) { // condition: never`, close: `    }`, alwaysWrap: false };
    }
  }

  // Expression or Reference — emit as comment with best-effort guard
  return { open: `    // condition: ${condition.kind} — emulated`, close: "", alwaysWrap: false };
}

/**
 * Convert an entry ID to a valid TypeScript identifier.
 * Prefixes with underscore if the first character is a digit.
 */
function toIdentifier(entryId: string): string {
  const sanitized = entryId.replace(/[^a-zA-Z0-9_$]/g, "_");
  if (/^[0-9]/.test(sanitized)) {
    return `_${sanitized}`;
  }
  return sanitized;
}
