// Emit: DaggerTargetGraph → TypeScript Dagger Module artifact.
// Spec 34 — §19.

import { DaggerTargetError } from "./errors.js";
import type { DaggerTargetGraph, DaggerStep, GeneratedArtifact } from "./types.js";

/**
 * Emit a DaggerTargetGraph as a TypeScript Dagger Module artifact.
 * Produces one <moduleName>.ts file.
 */
export function emitDagger(targetGraph: DaggerTargetGraph): readonly GeneratedArtifact[] {
  try {
    const fileName = `${targetGraph.moduleName}.ts`;
    return [{ path: fileName, content: emitModule(targetGraph) }];
  } catch (err) {
    throw new DaggerTargetError(
      `failed to emit Dagger module: ${err instanceof Error ? err.message : String(err)}`,
      "EMIT_FAILED",
      err,
    );
  }
}

/**
 * Generate the Dagger Module TypeScript file.
 */
function emitModule(graph: DaggerTargetGraph): string {
  const lines: string[] = [
    `// Generated by Sverka — Dagger Module target. Do not edit.`,
    `import { dag, object, func } from "@dagger.io/dagger";`,
    ``,
    `@object()`,
    `export class SverkaPipeline {`,
    `  @func()`,
    `  async ${toIdentifier(graph.entryId)}(): Promise<string> {`,
    `    let ctx = dag.git(".").tree();`,
  ];

  const stepById = new Map(graph.steps.map((s) => [s.stepId, s]));

  for (const stepId of graph.sequence) {
    const step = stepById.get(stepId);
    if (!step) continue;
    lines.push(...emitStep(step));
  }

  lines.push(`    return ctx.stdout();`);
  lines.push(`  }`);
  lines.push(`}`);
  lines.push("");

  return lines.join("\n");
}

/**
 * Emit a single step as Dagger withExec chain calls.
 */
function emitStep(step: DaggerStep): string[] {
  const lines: string[] = [];

  if (step.runtime.mode === "host") {
    lines.push(`    // Host runtime is unsupported by Dagger; using container context.`);
  }

  if (step.condition !== undefined) {
    lines.push(`    // Condition: emulated via if/else`);
    lines.push(`    if (true) {`);
  }

  if (step.retry !== undefined) {
    lines.push(`    // Retry wrapper (max ${step.retry.max} attempts)`);
    lines.push(`    for (let attempt = 0; attempt <= ${step.retry.max}; attempt++) {`);
    lines.push(`      try {`);
  }

  for (const command of step.commands) {
    const parts = command.split(/\s+/).filter(Boolean);
    const args = parts.map((p) => `"${p}"`).join(", ");
    if (step.timeout !== undefined) {
      lines.push(`    ctx = ctx.withExec([${args}]).withTimeout(${Math.ceil(step.timeout / 1000)});`);
    } else {
      lines.push(`    ctx = ctx.withExec([${args}]);`);
    }
  }

  if (step.matrix !== undefined) {
    lines.push(`    // Matrix: emulated via loop`);
    for (const [key, values] of Object.entries(step.matrix.dimensions)) {
      lines.push(`    for (const ${key} of [${values.map((v) => `"${v}"`).join(", ")}]) {`);
      lines.push(`      // matrix iteration: ${key}`);
      lines.push(`    }`);
    }
  }

  if (step.retry !== undefined) {
    lines.push(`        break;`);
    lines.push(`      } catch (err) {`);
    lines.push(`        if (attempt === ${step.retry.max}) throw err;`);
    lines.push(`      }`);
    lines.push(`    }`);
  }

  if (step.condition !== undefined) {
    lines.push(`    }`);
  }

  return lines;
}

/**
 * Convert an entry ID to a valid TypeScript identifier.
 */
function toIdentifier(entryId: string): string {
  return entryId.replace(/[^a-zA-Z0-9_$]/g, "_");
}
