// Emit: DaggerTargetGraph → TypeScript Dagger Module artifact.
// Spec 34 — §19.

import { DaggerTargetError } from "./errors.js";
import type { Condition } from "@sverka/workflow";
import type { DaggerTargetGraph, DaggerStep, GeneratedArtifact } from "./types.js";

/**
 * Emit a DaggerTargetGraph as a TypeScript Dagger Module artifact.
 * Produces one <moduleName>.ts file.
 */
export function emitDagger(targetGraph: DaggerTargetGraph): readonly GeneratedArtifact[] {
  try {
    const fileName = `${targetGraph.moduleName}.ts`;
    return [{ path: fileName, content: emitModule(targetGraph) }];
  } catch (err) {
    throw new DaggerTargetError(
      `failed to emit Dagger module: ${err instanceof Error ? err.message : String(err)}`,
      "EMIT_FAILED",
      err,
    );
  }
}

/**
 * Generate the Dagger Module TypeScript file.
 */
function emitModule(graph: DaggerTargetGraph): string {
  const defaultImage = graph.steps.find((s) => s.runtime.mode === "container" && s.runtime.image)?.runtime.image ?? "node:24";
  const lines: string[] = [
    `// Generated by Sverka — Dagger Module target. Do not edit.`,
    `import { dag, object, func } from "@dagger.io/dagger";`, // nosemgrep: missing-template-string-indicator
    ``,
    `@object()`,
    `export class SverkaPipeline {`,
    `  @func()`,
    `  async ${toIdentifier(graph.entryId)}(): Promise<string> {`, // nosemgrep: missing-template-string-indicator, html-in-template-string
    `    let ctx = dag.container().from(${JSON.stringify(defaultImage)}).withMountedDirectory("/src", dag.git(".").tree()).withWorkdir("/src");`,
    `    let _failed = false;`,
  ];

  const stepById = new Map(graph.steps.map((s) => [s.stepId, s]));

  for (const stepId of graph.sequence) {
    const step = stepById.get(stepId);
    if (!step) continue;
    lines.push(...emitStep(step));
  }

  lines.push(...[
    `    if (_failed) throw new Error("pipeline failed");`,
    `    return ctx.stdout();`,
    `  }`,
    `}`,
    "",
  ]);

  return lines.join("\n");
}

/**
 * Emit a single step as Dagger withExec chain calls.
 */
function emitStep(step: DaggerStep): string[] {
  const lines: string[] = [...emitRuntimeModeLines(step)];

  const guard = conditionGuard(step.condition);

  if (guard.open) {
    lines.push(guard.open);
  }

  if (step.retry !== undefined) {
    lines.push(...emitRetryBlock(step));
  } else {
    lines.push(...emitCommands(step));
    // Non-retry path: force execution and catch errors to set _failed
    lines.push(`    try { ctx.stdout(); } catch { _failed = true; }`); // nosemgrep: missing-template-string-indicator
  }

  if (step.matrix !== undefined) {
    lines.push(...emitMatrix(step.matrix));
  }

  // Track failure for condition guards
  if (step.condition?.kind === "status" && step.condition.status === "always") {
    lines.push(`    try { /* always: swallow errors */ } catch { /* no-op */ }`); // nosemgrep: missing-template-string-indicator
  }

  if (guard.close) {
    lines.push(guard.close);
  }

  return lines;
}

/**
 * Emit runtime mode lines (host warning, container image switch).
 */
function emitRuntimeModeLines(step: DaggerStep): string[] {
  const lines: string[] = [];
  if (step.runtime.mode === "host") {
    lines.push(`    // Host runtime is unsupported by Dagger; using container context.`);
  }
  // Switch to a different container image when the step declares one.
  // JSON.stringify escapes quotes, backslashes, and newlines so a malicious
  // or malformed image name cannot break out of the TypeScript string literal.
  if (step.runtime.mode === "container" && step.runtime.image) {
    lines.push(`    ctx = dag.container().from(${JSON.stringify(step.runtime.image)}).withMountedDirectory("/src", dag.git(".").tree()).withWorkdir("/src");`);
  }
  return lines;
}

/**
 * Emit the retry wrapper block for a step.
 */
function emitRetryBlock(step: DaggerStep): string[] {
  const lines: string[] = [];
  lines.push(...[
    `    // Retry wrapper (max ${step.retry!.max} attempts)`,
    `    for (let attempt = 0; attempt < ${step.retry!.max}; attempt++) {`,
    `      try {`,
    `        let retryCtx = ctx;`,
  ]);
  for (const command of step.commands) {
    const cmdStr = JSON.stringify(command);
    if (step.timeout !== undefined) {
      lines.push(`    // timeout: ${Math.ceil(step.timeout / 1000)}s (Dagger has no withTimeout; enforced by runner)`);
    }
    lines.push(`        retryCtx = retryCtx.withExec(["sh", "-c", ${cmdStr}]);`);
  }
  lines.push(...[
    `        retryCtx.stdout(); // execute graph to surface errors`,
    `        ctx = retryCtx;`,
    `        break;`,
    `      } catch (err) {`,
    `        if (attempt === ${step.retry!.max - 1}) { _failed = true; }`, // nosemgrep: missing-template-string-indicator
    `      }`,
    `    }`,
  ]);
  return lines;
}

/**
 * Emit non-retry command lines for a step.
 */
function emitCommands(step: DaggerStep): string[] {
  const lines: string[] = [];
  for (const command of step.commands) {
    const cmdStr = JSON.stringify(command);
    if (step.timeout !== undefined) {
      lines.push(`    // timeout: ${Math.ceil(step.timeout / 1000)}s (Dagger has no withTimeout; enforced by runner)`);
    }
    lines.push(`    ctx = ctx.withExec(["sh", "-c", ${cmdStr}]);`);
  }
  return lines;
}

/**
 * Emit matrix iteration lines.
 */
function emitMatrix(matrix: DaggerStep["matrix"]): string[] {
  if (matrix === undefined) return [];
  const lines: string[] = [`    // Matrix: emulated via loop`];
  for (const [key, values] of Object.entries(matrix.dimensions)) {
    const serializedValues = values.map((v) => JSON.stringify(String(v))).join(", ");
    lines.push(`    for (const ${key} of [${serializedValues}]) {`);
    lines.push(`      // matrix iteration: ${key}`);
    lines.push(`    }`);
  }
  return lines;
}

/**
 * Generate condition guard lines for a step.
 */
function conditionGuard(condition: Condition | undefined): { open: string; close: string; alwaysWrap: boolean } {
  if (condition === undefined) {
    return { open: "", close: "", alwaysWrap: false };
  }

  if (condition.kind === "status") {
    switch (condition.status) {
      case "success":
        return { open: `    if (!_failed) {`, close: `    }`, alwaysWrap: false };
      case "failure":
        return { open: `    if (_failed) {`, close: `    }`, alwaysWrap: false };
      case "always":
        return { open: "", close: "", alwaysWrap: true };
      case "never":
        return { open: `    if (false) { // condition: never`, close: `    }`, alwaysWrap: false };
    }
  }

  // Expression or Reference — cannot be evaluated at compile time
  return { open: `    // WARNING: condition kind '${condition.kind}' cannot be evaluated at compile time; step is unconditional`, close: "", alwaysWrap: false };
}

/**
 * Convert an entry ID to a valid TypeScript identifier.
 * Prefixes with underscore if the first character is a digit.
 */
function toIdentifier(entryId: string): string {
  const sanitized = entryId.replace(/[^a-zA-Z0-9_$]/g, "_");
  if (/^\d/.test(sanitized)) {
    return `_${sanitized}`;
  }
  return sanitized;
}
