name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  actions: read
  contents: write

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          filter: tree:0
          fetch-depth: 0

      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - run: bun install --frozen-lockfile
      - uses: nrwl/nx-set-shas@v4

      - run: bunx nx affected -t lint test build
      - run: bunx nx fix-ci
        if: always()